<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.CN.NET.Sdk/14.0.1">
	<PropertyGroup>
    <Platforms>x64</Platforms>
		<Authors>53m1k0l0n/Gidedin</Authors>
		<Version>5.3.2.4</Version>
		<Description>LazyLoot plugin.</Description>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ECommons" Version="3.1.0.5" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
		<ProjectReference Include="..\..\PunishLib\PunishLib\PunishLib.csproj" />
	</ItemGroup>

    <ItemGroup>
        <None Update="LazyLoot.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
